stori6/urls.py
from django.urls import path
from . import views

app_name = 'stori6'

urlpatterns = [
    path('',views.createKegiatan,name='kegiatan'),
    path('create/<int:siswa_id>', views.createSiswa, name='create'),
    
   
]

tdd/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stori6.urls'))
]

stori6/models.py
from django.db import models

# Create your models here.

class listKegiatan(models.Model):
	namaKegiatan = models.TextField(max_length=300)
	def __str__(self):
		return self.namaKegiatan



class listSiswa(models.Model):
	namaSiswa = models.TextField(max_length=300)
	kegiatan = models.ForeignKey(listKegiatan, on_delete=models.CASCADE)
	def __str__(self):
		return self.namaSiswa

stori6/forms.py
from django.forms import ModelForm
from .models import listKegiatan,listSiswa
from django import forms

class formKegiatan(forms.Form):
	namaKegiatan = forms.CharField(max_length=300,required=True)

class formSiswa(forms.Form):
	namaSiswa = forms.CharField(max_length=300)
        

stori6/views.py
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from django.http import HttpResponseRedirect

# Create your views here.
def createKegiatan(request):
	kegiatan= listKegiatan.objects.all()
	kegiatann=formKegiatan(request.POST or None)
	context={
		'kegiatan':kegiatan,
		'kegiatann':kegiatann
	}
	if request.method=='POST':
		if kegiatann.is_valid():
			kegiatan.create(
				namaKegiatan=kegiatann.cleaned_data.get('namaKegiatan')
				)
	return render(request,'kegiatan.html',context)

def createSiswa(request, siswa_id):
	siswa= listKegiatan.objects.get(id=siswa_id)
	siswaTarget = listSiswa.objects.all()
	form_siswa = formSiswa(request.POST or None)
	context={
		'siswa':siswa,
		'form_siswa':form_siswa,
		'siswa_target':siswaTarget,
	}
	if request.method=='POST':
		if form_siswa.is_valid():
			siswaTarget.create(
					namaSiswa=form_siswa.cleaned_data.get('namaSiswa'),
					kegiatan=siswa
				)
	return render(request,'jadwal_siswa.html',context)

stori6/templates/jadwal_siswa.html
<!DOCTYPE html>
<html>
<head>
	<title>Kegiatan</title>
	{% include "navbar.html" %}
</head>
<body>
	<h2>Jadwal Kegiatan</h2>

	<form method="POST">
	{% csrf_token %}
	<table>
		{{form_siswa.as_table}}
	</table>
	<button type="Submit" name="submit">Submit</button>

	<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Nama Siswa</th>
    </tr>
    </thead>
    <tbody>
    	{% for sis in siswa_target %}
    	<tr>
            {% if sis.kegiatan == siswa %}
    		<th scope="row">{{sis.namaSiswa}}</th>
            {% endif %} 
    	</tr>
    </tbody>
    {% endfor %}
</body>
</html>

stori6/templates/kegiatan.html
<!DOCTYPE html>
<html>
<head>
	<title>Kegiatan</title>
	{% include "navbar.html" %}
</head>
<body>
	<h2>Jadwal Kegiatan</h2>

	<form method="POST">
	{% csrf_token %}
	<table>
		{{kegiatann.as_table}}
	</table>
	<button type="Submit" name="submit">Submit</button>

	<table class="table table-dark table-striped">
  <thead>
    <tr>
      <th scope="col">Nama Kegiatan</th>
    </tr>
    </thead>
    <tbody>
    	{% for keg in kegiatan %}
    	<tr>
    		<th scope="row">{{keg.namaKegiatan}}</th>
    		<td><a href="{% url 'stori6:create' siswa_id=keg.id %}" class="btn btn-danger">Lihat/Add Siswa</a></td>
    	</tr>
    </tbody>
    {% endfor %}
</body>
</html>

stori6/templates/navbar.html
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">LiveDemo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
{#         <a class="nav-link" href="/jadwal">Jadwal <span class="sr-only">(current)</span></a> #}
        <a class="nav-link" href="/">Kegiatan <span class="sr-only">(current)</span></a>
      </li>
  </ul>
</div>
</nav>